[features]
seeds = false
skip-lint = false

[programs.localnet]
rox_anchor = "U91owoSZLda4pZf2Qw8Xz3rS5v2vvi95kSev33KTivR"

[provider]
cluster = "Localnet"
wallet = ".solana/rox-anchor-localnet-payer.json"

[scripts]
test = "cargo test --workspace"
