[features]
seeds = false
skip-lint = false

[programs.localnet]
rox_anchor = "FiUY5M3a8xRHCgCfNzqNe5qATKUa3fk2chHFsJGdEitk"

[programs.devnet]
rox_anchor = "FiUY5M3a8xRHCgCfNzqNe5qATKUa3fk2chHFsJGdEitk"

[programs.testnet]
rox_anchor = "FiUY5M3a8xRHCgCfNzqNe5qATKUa3fk2chHFsJGdEitk"

[provider]
cluster = "Localnet"
wallet = ".solana/rox-anchor-localnet-payer.json"

[scripts]
test = "cargo test --workspace"
testnet_deploy_drill_check = "bash scripts/check_testnet_deploy_drill.sh ."
