#!/usr/bin/env bash
set -euo pipefail

# RO:WHAT — Generate a repo-wide ROX Anchor text/codebundle review artifact.
# RO:WHY — One-file share/review artifact for docs, scripts, scaffold, and future placeholders without running builds.
# RO:OUTPUT — Default: ./CODEBUNDLE.md, or the second argument.
# RO:INVARIANTS — stable sort; no secrets; no target/node_modules/build outputs; source of truth remains repo files.
# RO:SECURITY — skips secret/key-shaped files and local generated artifacts; does not run cargo/npm/Anchor/Solana/deploy commands.
# RO:TEST — bash -n scripts/make_codebundle.sh && bash scripts/make_codebundle.sh . CODEBUNDLE.md.

ROOT="${1:-.}"
OUT="${2:-CODEBUNDLE.md}"

cd "$ROOT"

EXCLUDE_SEGMENTS=(
  "/.git/"
  "/target/"
  "/node_modules/"
  "/dist/"
  "/build/"
  "/coverage/"
  "/.cache/"
  "/.turbo/"
  "/.anchor/"
  "/test-ledger/"
  "/.idea/"
  "/.vscode/"
)

EXCLUDE_NAMES=(
  ".DS_Store"
  "CODEBUNDLE.md"
  "CODEBUNDLE_RS.md"
)

SENSITIVE_PATTERNS=(
  ".env"
  ".env.*"
  "*.pem"
  "*.key"
  "*.p12"
  "*.pfx"
  "id.json"
  "keypair.json"
  "wallet.json"
  "payer.json"
  "authority.json"
  "mint-authority.json"
  "upgrade-authority.json"
  "program-authority.json"
  "deploy-authority.json"
  "admin.json"
  "owner.json"
  "validator-keypair.json"
  "faucet-keypair.json"
)

is_excluded_path() {
  local p="$1"
  local seg
  for seg in "${EXCLUDE_SEGMENTS[@]}"; do
    if [[ "$p" == *"$seg"* ]]; then
      return 0
    fi
  done

  local base
  base="$(basename "$p")"
  local name
  for name in "${EXCLUDE_NAMES[@]}"; do
    if [[ "$base" == "$name" ]]; then
      return 0
    fi
  done

  return 1
}

is_sensitive_path() {
  local p="$1"
  local base
  base="$(basename "$p")"

  local pat
  for pat in "${SENSITIVE_PATTERNS[@]}"; do
    case "$base" in
      $pat) return 0 ;;
    esac
  done

  case "$p" in
    */secrets/*|*/private/*|*/credentials/*|*/tokens/*|*/auth/*|*/target/deploy/*.json|*/programs/*/target/deploy/*.json)
      return 0
      ;;
  esac

  return 1
}

is_text_or_empty() {
  local f="$1"
  if [ ! -s "$f" ]; then
    return 0
  fi

  grep -Iq . "$f"
}

anchor() {
  echo "$1" \
    | tr '[:upper:]' '[:lower:]' \
    | sed -E 's/[^a-z0-9 _-]+//g; s/[[:space:]]+/-/g; s/-+/-/g'
}

fence_lang() {
  case "$1" in
    *.rs) echo "rust" ;;
    *.sh) echo "bash" ;;
    *.md|*.MD) echo "markdown" ;;
    *.toml) echo "toml" ;;
    *.json) echo "json" ;;
    *.ts|*.tsx) echo "typescript" ;;
    *.js|*.jsx) echo "javascript" ;;
    *.yml|*.yaml) echo "yaml" ;;
    *.gitignore|.gitignore|*.gitattributes|.gitattributes) echo "text" ;;
    *) echo "text" ;;
  esac
}

FILES_NUL="$(mktemp)"
FILES_SORTED_LF="$(mktemp)"
TREE_TMP="$(mktemp)"
SKIPPED_TMP="$(mktemp)"
trap 'rm -f "$FILES_NUL" "$FILES_SORTED_LF" "$TREE_TMP" "$SKIPPED_TMP"' EXIT

while IFS= read -r -d '' f; do
  [[ "$f" != ./* ]] && f="./$f"

  if is_excluded_path "$f"; then
    continue
  fi

  if is_sensitive_path "$f"; then
    printf '%s\n' "${f#./}" >> "$SKIPPED_TMP"
    continue
  fi

  if is_text_or_empty "$f"; then
    printf '%s\0' "$f" >> "$FILES_NUL"
  else
    printf '%s\n' "${f#./} (binary skipped)" >> "$SKIPPED_TMP"
  fi
done < <(find . -type f -print0)

tr '\0' '\n' < "$FILES_NUL" | LC_ALL=C sort > "$FILES_SORTED_LF"

FILE_COUNT="$(wc -l < "$FILES_SORTED_LF" | tr -d ' ')"

{
  echo "./"
  awk '
    function indent(n){ s=""; for(i=0;i<n;i++) s=s"  "; return s }
    {
      p=$0
      sub(/^\.\//, "", p)
      n=split(p, parts, "/")
      cur=""
      for(i=1;i<=n;i++){
        cur = (cur=="" ? parts[i] : cur"/"parts[i])
        if(!seen[cur]++){
          depth=i
          if(i<n){ print indent(depth) parts[i] "/" }
          else   { print indent(depth) parts[i] }
        }
      }
    }
  ' "$FILES_SORTED_LF"
} > "$TREE_TMP"

NOW="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"
GIT_SHA="$(git rev-parse --short HEAD 2>/dev/null || echo "nogit")"
GIT_DIRTY=""
if git diff --quiet 2>/dev/null; then :; else GIT_DIRTY=" (dirty)"; fi

{
  echo "<!-- Generated by scripts/make_codebundle.sh on ${NOW} -->"
  echo "# Code Bundle — ROX Anchor"
  echo
  echo "> Generated for review/sharing. Source of truth remains the repo."
  echo "> Includes text files and empty placeholders. Excludes secrets, local metadata, build outputs, dependency folders, and generated codebundles."
  echo "> This artifact is not runtime authorization."
  echo
  echo "- Root: \`$(pwd)\`"
  echo "- Git: \`${GIT_SHA}${GIT_DIRTY}\`"
  echo "- Files: \`${FILE_COUNT}\`"
  echo
  echo "## Non-Authorization Notice"
  echo
  echo "This codebundle does not authorize ROX runtime, Solana runtime, bridge runtime, staking, liquidity, exchange-facing logic, or external settlement."
  echo
  echo "## File Tree"
  echo '```text'
  cat "$TREE_TMP"
  echo '```'
  echo
  echo "## Skipped Files"
  if [ -s "$SKIPPED_TMP" ]; then
    echo '```text'
    LC_ALL=C sort "$SKIPPED_TMP"
    echo '```'
  else
    echo
    echo "None."
  fi
  echo
  echo "## Table of Contents"
  while IFS= read -r f; do
    rel="${f#./}"
    a="$(anchor "$rel")"
    echo "- [$rel](#${a})"
  done < "$FILES_SORTED_LF"
  echo

  while IFS= read -r f; do
    rel="${f#./}"
    a="$(anchor "$rel")"
    lang="$(fence_lang "$rel")"

    echo "---"
    echo
    echo "## $rel"
    echo
    echo "<a id=\"${a}\"></a>"
    echo

    if [ ! -s "$f" ]; then
      echo '```text'
      echo "(empty placeholder file)"
      echo '```'
      echo
      continue
    fi

    echo "\`\`\`${lang}"
    cat "$f"
    echo
    echo '```'
    echo
  done < "$FILES_SORTED_LF"
} > "$OUT"

echo "Wrote $OUT"
